### ISSUE TITLE
Superscript and subscript Numbers missing

### ISSUE THREAD

**Issue by leoschul** [liberationfonts/liberation-fonts#40]
Hi,

is it possible to add all superscript and subscript numbers in the next version?

- **Codepoint - Mono - Sans - Serif - Unicode-Name - Symbol**
- 2074     -  missing -   _existing_ -  _existing_ -   SUPERSCRIPT FOUR - ⁴
- 2075    -   missing -   _existing_ -  _existing_ -  SUPERSCRIPT FIVE - ⁵
- 2076     -  missing -   missing -   missing -   SUPERSCRIPT SIX - ⁶
- 2077     -  missing -   _existing_ -  _existing_  - SUPERSCRIPT SEVEN - ⁷
- 2078     -  missing -   _existing_ -  _existing_  - SUPERSCRIPT EIGHT - ⁸
- 2079     -  missing -   missing -  missing  -  SUPERSCRIPT NINE - ⁹
- 2080     -  missing -   missing -   missing -   SUBSCRIPT ZERO - ₀
- 2081     -  missing -   missing -   missing -   SUBSCRIPT ONE - ₁
- 2082     -  missing -   missing -   missing -   SUBSCRIPT TWO - ₂
- 2083     -  missing -   missing -   missing -   SUBSCRIPT THREE - ₃
- 2084     -  missing -   missing -   missing -   SUBSCRIPT FOUR - ₄
- 2085     -  missing -   missing -   missing -   SUBSCRIPT FIVE - ₅
- 2086     -  missing -   missing -   missing -   SUBSCRIPT SIX - ₆
- 2087     -  missing -   missing -   missing -   SUBSCRIPT SEVEN - ₇
- 2088     -  missing -   missing -   missing -   SUBSCRIPT EIGHT - ₈
- 2089     -  missing -   missing -   missing -   SUBSCRIPT NINE - ₉

**Comment by m-m-moeller** [comment]
Solving this issue would be very welcome with respect to [DIN SPEC 91379](https://www.din.de/en/wdc-beuth:din21:301228458) : "Characters in Unicode for the electronic processing of names and data exchange in Europe; with digital attachment"
The German [IT Planning Concil](https://www.it-planungsrat.de/EN/home/home_node.html) requires future conformance with DIN SPEC 91379, see [corresponding decisions (in german)](https://www.xoev.de/die_standards/lateinische_zeichen_in_unicode-4813) 

The codepoints mentioned above are part of DIN Sepc 91379 datatype D, which is proposed to be used for "names of legal entities and for product names".

The "DIN Standards Committee Information Technology and selected IT Applications" ist already working on a [project for DIN 91379](https://www.din.de/en/getting-involved/standards-committees/nia/projects/wdc-proj:din21:315059196?destinationLanguage=&sourceLanguage=en), which ist described as follows: "This standard is based on the Unicode standard and is primarily aimed at authorities and organisations that operate IT procedures that serve the exchange of data between authorities or with citizens and business."

**Comment by kenmcd** [comment]
> Solving this issue would be very welcome with respect to [DIN SPEC 91379](https://www.din.de/en/wdc-beuth:din21:301228458) : "Characters in Unicode for the electronic processing of names and data exchange in Europe; with digital attachment"
> The German [IT Planning Concil](https://www.it-planungsrat.de/EN/home/home_node.html) requires future conformance with DIN SPEC 91379, see [corresponding decisions (in german)](https://www.xoev.de/die_standards/lateinische_zeichen_in_unicode-4813)
 
Please post the document. 
It would be nice to know what is actually being requested/required.
A simple list of the Unicode code points would suffice.
It is so annoying that these EU standards bodies hide all the "public" documents behind log-ins and paywalls.
Also it appears the document is only available in German.
Does the info exist anywhere in English?

**Comment by msg-tbrtz** [comment]
If the project is open for contributions, I could help out in adding the missing glyphs - would this be welcomed?

**Comment by m-m-moeller** [comment]
@kenmcd : 
Unfortunatly the documents are available in german only.
A commented, german version of DIN SPEC 91379 (with german FAQ's) is available for free download at https://www.xoev.de/sixcms/media.php/13/StringLatin%2012.zip
The ZIP-File includes - among other documents - "latinchars.xml" (complete list of all require codepoints in xml format), "2018-11-15_din-spec-91379.xlsx" (complete list of all require codepoints in Excel format) and "din-91379-datatypes.xsd" (definition of the data types). Which one fits your needs best?

**Comment by kenmcd** [comment]
> Which one fits your needs best?

All of them. Fantastic. Thank you!
Even in the German PDF the list is all Unicode code points and descriptions.
I can easily compare these lists to other standardized character lists from Adobe, Linotype, Microsoft, etc.
Thanks again.

**Comment by msg-tbrtz** [comment]
@kenmcd Is there an approximate timeline for the next release including those glyphs? :-)

**Comment by vishalvvr** [comment]
> @kenmcd Is there an approximate timeline for the next release including those glyphs? :-)

This bug is already fixed and will be available in v2.1.4 release.
I am currently working on one more fix then we are good to make v2.1.4 release, which will be done maximum by end of this week. 
Thank you everyone for all your inputs and discussion :)

**Comment by kenmcd** [comment]
v2.1.4 Sans still has some issues
2079 the superscript 9 is still missing.
And the added superscript 6 (2076) is not the same weight as the original 1-4,7, 8.
And there is no superscript zero.

Also the added subscripts do not match the weight of the original superscripts.

**Comment by vishalvvr** [comment]
> v2.1.4 Sans still has some issues
> 2079 the superscript 9 is still missing.
> And the added superscript 6 (2076) is not the same weight as the original 1-4,7, 8.
> And there is no superscript zero.
> 
> Also the added subscripts do not match the weight of the original superscripts.

Hi @kenmcd,
I have made the above requested changes to only LiberationSans-Bold [1].
Could you please review and confirm the changes so that i can update it to other variants as well.

[1] https://vishalvvr.fedorapeople.org/LiberationSans-Bold.ttf 

Thank you:)

**Comment by msg-tbrtz** [comment]
@vishalvvr While I'm not @kenmcd , as far as I can tell, your new version has fixed the issues! Looking forward to a release. :-)

**Comment by kenmcd** [comment]
> 
> 
> > v2.1.4 Sans still has some issues
> > 2079 the superscript 9 is still missing.
> > And the added superscript 6 (2076) is not the same weight as the original 1-4,7, 8.
> > And there is no superscript zero.
> > Also the added subscripts do not match the weight of the original superscripts.
> 
> Hi @kenmcd,
> I have made the above requested changes to only LiberationSans-Bold [1].
> Could you please review and confirm the changes so that i can update it to other variants as well.
> 
> [1] https://vishalvvr.fedorapeople.org/LiberationSans-Bold.ttf
> 
> Thank you:)

The glyphs all appear to be there and at correct weights.
So it looks ready to do the other weights as well.
Cannot fully test the superscripts as the OpenType feature is not there (assume this is a test font).
